encryptionsalt: v1:Zb/woMbCPK0=:v1:TSFcMDF6IU79RLed:EFi5krjwGMbVscwL43OWbfcQT2H0cQ==
config:
  sudoku-race:pat:
    secure: v1:6OMHxxF2TpUve4IP:bQHt85wLreSNA1yJEPm0M+R9DG3Z8/MrhiFZgf33eNskPV6mNjpP416fzIYYkXwGrKX1YoMfUAo=
