name: Push to master
on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  master:
    name: Master
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        stack:
          - metrics-server
    steps:
      - uses: actions/checkout@v2.3.4
      - name: asdf setup
        uses: asdf-vm/actions/install@v1.0.1

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.CIVO_KUBECONFIG }}

      - run: |
          kubectl get pods --all-namespaces

      - name: Deploy
        working-directory: "./operations"
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        run: |
          pulumi up -s ${{ matrix.stack }} --yes --skip-preview --suppress-outputs --suppress-permalink
