name: Push to master
on:
  pull_request: {}
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  ci:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Fetch python version to match what is in .tool-versions
        id: python-version
        run: |
          version="$(cat .tool-versions | grep 'python' | awk '{print $2}')"
          echo "::set-output name=version::${version}"
          echo $version

        # We install via setup-python because GitHub caches version artifacts
        # We could install via asdf but for CI that would be far too slow. It takes ~5-10 minutes each time
        # This is fine for local development since it only has to happen once instead of every build
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ steps.python-version.outputs.version }}

      - name: Install asdf on the Action Runner
        uses: asdf-vm/actions/setup@v1
        with:
          asdf_branch: "v0.8.0"
      - name: Fetch asdf plugins repo
        uses: asdf-vm/actions/plugins-add@v1
      - name: Install poetry
        run: |
          asdf install poetry
      - name: Run black linter
        run: |
          poetry run black --check .
      - name: Run pytest
        run: |
          poetry run pytest --cov=./sudokurace ./tests

  stack-matrix:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.stack-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2.3.4
      - id: stack-matrix
        # Find all leaf level directories and reduce into JSON object
        run: |
          matrix="$(find operations/stacks -mindepth 1 -maxdepth 1 -type d | cut -c 19- | jq -R '[.]' | jq -sc 'add | {stack: .}')"
          echo "::set-output name=matrix::${matrix}"
  deploy:
    needs:
      - stack-matrix
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.stack-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install asdf on the Action Runner
        uses: asdf-vm/actions/setup@v1
        with:
          asdf_branch: "v0.8.0"
      - name: Fetch asdf plugins repo
        uses: asdf-vm/actions/plugins-add@v1
      - name: Install just pulumi
        run: |
          asdf install pulumi

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.CIVO_KUBECONFIG }}

      # pulumi dependencies
      - name: Cache pulumi dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-pulumi
        with:
          path: |
            ~/.npm
            ~/.pulumi/plugins
            ./operations/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install pulumi dependencies
        working-directory: "./operations"
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        run: |
          npm ci

      - name: Create lock
        uses: abatilo/github-action-locks@master
        with:
          name: "sudoku-race-${{ matrix.stack }}"

      - name: Preview
        if: github.event_name == 'pull_request'
        working-directory: "./operations"
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        run: |
          pulumi preview -s ${{ matrix.stack }} --diff --suppress-outputs --suppress-permalink

      - name: Deploy
        if: github.event_name == 'push'
        working-directory: "./operations"
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        run: |
          pulumi up -s ${{ matrix.stack }} --yes --skip-preview --suppress-outputs --suppress-permalink
