name: Push to master
on:
  push:
    branches:
      - master

jobs:
  master:
    name: Master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: asdf setup
        uses: asdf-vm/actions/install@v1.0.1

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.CIVO_KUBECONFIG }}
        id: setcontext

      - run: |
          kubectl get pods --all-namespaces
