name: Push to master
on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  stack-matrix:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.stack-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2.3.4
      - id: stack-matrix
        # Find all leaf level directories and reduce into JSON object
        run: |
          find operations/stacks -mindepth 1 -maxdepth 1 -type d | cut -c 19- | jq -R '[.]' | jq -sc 'add | {stack: .}'
          matrix="$(find operations/stacks -mindepth 1 -maxdepth 1 -type d | cut -c 19- | jq -R '[.]' | jq -sc 'add | {stack: .}')"
          echo "::set-output name=matrix::${matrix}"
  master:
    name: Master
    needs:
      - stack-matrix
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.stack-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: "Filter out unneeded dependencies"
        run: |
          cat .tool-versions | grep -vE "kubectl|poetry|python" > .filtered
          mv .filtered .tool-versions

      - name: asdf setup
        uses: asdf-vm/actions/install@v1.0.1

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.CIVO_KUBECONFIG }}

      # npm dependencies
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install npm dependencies
        working-directory: "./operations"
        run: |
          npm ci

      - name: Create lock
        uses: abatilo/github-action-locks@master
        with:
          name: "sudoku-race-${{ matrix.stack }}"

      - name: Deploy
        working-directory: "./operations"
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        run: |
          pulumi up -s ${{ matrix.stack }} --yes --skip-preview --suppress-outputs --suppress-permalink
