name: Semantic PR
on: pull_request

jobs:
  semantic-pr:
    runs-on: ubuntu-20.04
    steps:
      - uses: amannn/action-semantic-pull-request@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
